services:
  backend:
    image: curro85/blog-back
    container_name: blog-backend
    ports:
      - "3000:3000"
    volumes:
      - sqlite_data:/app/db.sqlite
    env_file:
      - ../backend/src/.env

  frontend:
    image: curro85/blog-front
    container_name: blog-frontend
    ports:
      - "8080:80"
    env_file:
      - ../frontend/.env

volumes:
  sqlite_data:
